name: NoPhantom
version: '${projectVersion}'
main: net.okocraft.nophantom.Main
api-version: 1.19
folia-supported: true
permissions:
  nophantom.denyspawn:
    default: false
  nophantom.denyspawn.multi:
    default: false
